spring.application.name=webapp

# DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/concert_booking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh

spring.datasource.username=root
spring.datasource.password=ninh1103
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# SQL INIT
spring.sql.init.mode=never

# SERVER
server.port=8080